services:
  postgres:
    image: postgres:16-alpine
    container_name: bikecare-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: bikecaredb
      POSTGRES_USER: bikecare
      POSTGRES_PASSWORD: bikecare
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
