spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bikecaredb
    username: ${DB_USERNAME:bikecare}
    password: ${DB_PASSWORD:bikecare}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

server:
  port: 8080

# Strava OAuth (volitelné, pro skeleton)
strava:
  client-id: ${STRAVA_CLIENT_ID:}
  redirect-uri: ${STRAVA_REDIRECT_URI:http://localhost:8080/api/strava/oauth/callback}
