spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bikecaredb
    username: bikecare
    password: bikecare
  jpa:
    hibernate:
      ddl-auto: update   # JEN na první start: vytvoří chybějící tabulky

security:
  jwt:
    secret: 74111c60cc14ab63d75c7ce8c6aee34ec21f1f012f1388acef999df84c5f8a8f
    expiration: 43200000
