spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/bikecaredb
    username: ${BC_DB_USER:bikecare}
    password: ${BC_DB_PASS:bikecare}
    hikari:
      maximum-pool-size: 5
