name: backend-ci

on:
  push:
    paths:
      - 'src/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - '.github/workflows/backend-ci.yml'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: bikecare
          POSTGRES_PASSWORD: bikecare
          POSTGRES_DB: bikecare
        options: >-
          --health-cmd="pg_isready -U bikecare -d bikecare"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20
        ports:
          - 5432:5432

    env:
      BC_DB_URL: jdbc:postgresql://localhost:5432/bikecare
      BC_DB_USER: bikecare
      BC_DB_PASS: bikecare
      BC_JWT_SECRET: dummy-secret-for-ci

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Wait for Postgres
        run: |
          for i in {1..60}; do
            pg_isready -h localhost -p 5432 -U bikecare && break
            sleep 1
          done

      - name: Build & Test
        run: ./gradlew clean test build --no-daemon
